# Copyright 2026 GCSA
# Intended path: chrome/browser/ui/webui/aegis/BUILD.gn

source_set("aegis") {
  sources = [
    "aegis_ui.cc",
    "aegis_ui.h",
    "aegis_ui_handler.cc",
    "aegis_ui_handler.h",
  ]
  deps = [
    "//base",
    "//chrome/browser/aegis",
    "//chrome/browser/aegis:agent_core",
    "//chrome/browser/download",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/resources/aegis:resources",
    "//chrome/common",
    "//chrome/common/aegis",
    "//chrome/services/aegis_torrent/public/mojom",
    "//content/public/browser",
    "//mojo/public/cpp/bindings",
    "//third_party/blink/public/common",
    "//ui/base",
    "//ui/webui",
  ]
  if (!is_android) {
    deps += [
      "//chrome/browser/ui/browser_window",
      "//chrome/browser/ui/side_panel:side_panel_views_dependent",
      "//chrome/browser/ui/tabs:tab_strip",
    ]
  }

  deps += [ "//chrome/browser:browser_process" ]
}
