# Copyright 2026 GCSA
# Intended path: chrome/browser/aegis/access/BUILD.gn

import("//testing/test.gni")

source_set("access_browser_request_adapter") {
  sources = [
    "access_browser_request_adapter.cc",
    "access_browser_request_adapter.h",
  ]
  deps = [
    ":access_network_context_transport",
    "//base",
    "//chrome/browser/aegis",
    "//chrome/browser/aegis:profile_support",
    "//chrome/browser/profiles:profile",
    "//chrome/common:channel_info",
    "//components/aegis_access",
    "//components/aegis_access:browser_request_metadata_seed",
    "//components/version_info:channel",
    "//content/public/browser",
    "//net",
    "//url",
  ]
}

source_set("access_network_context_transport") {
  sources = [
    "access_network_context_transport.cc",
    "access_network_context_transport.h",
  ]
  deps = [
    "//base",
    "//chrome/browser/aegis:profile_support",
    "//chrome/browser/profiles:profile",
    "//components/aegis_access",
    "//mojo/public/cpp/bindings",
    "//net",
    "//services/network/public/mojom",
    "//url",
  ]
}

source_set("access_rule_store") {
  sources = [
    "access_rule_store.cc",
    "access_rule_store.h",
  ]
  deps = [
    "//base",
    "//components/aegis_access",
    "//net",
    "//sql",
    "//url",
  ]
}

test("access_network_context_transport_unittests") {
  sources = [ "access_network_context_transport_unittest.cc" ]
  deps = [
    ":access_network_context_transport",
    "//base/test:run_all_unittests",
    "//base/test:test_support",
    "//chrome/browser/profiles:test_support",
    "//components/aegis_access",
    "//mojo/public/cpp/bindings",
    "//net",
    "//services/network:network_service",
    "//services/network/public/mojom",
    "//testing/gtest",
    "//url",
  ]
}

test("access_rule_store_unittests") {
  sources = [ "access_rule_store_unittest.cc" ]
  deps = [
    ":access_rule_store",
    "//base/test:run_all_unittests",
    "//base/test:test_support",
    "//components/aegis_access",
    "//net",
    "//sql",
    "//testing/gtest",
    "//url",
  ]
}
